CREATE TABLE IF NOT EXISTS alunos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT NOT NULL,
  cpf UNSIGNED BIG INT NOT NULL,
  situacao TEXT NOT NULL,
  CHECK (situacao IN ('CONCLUIDO', 'EVADIDO', 'CADASTRADO' , 'MATRICULADO'))
);